# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.6.3

variables:
  JEKYLL_ENV: production

before_script:
  - make pre_deploy

deploy:
  stage: deploy
  script:
    - make deploy
  artifacts:
    paths:
      - _site
  only:
    - master
