# This file is a template, and might need editing before it works on your project.
# Template project: https://gitlab.com/pages/jekyll
# Docs: https://docs.gitlab.com/ce/pages/
image: ruby:2.6.3

variables:
  JEKYLL_ENV: production

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - apt-get update && apt-get -y install rsync
  - bundle install

deploy_staging:
  stage: deploy
  script:
    - make deploy_staging
  artifacts:
    paths:
      - _site
  except:
    - master

deploy:
  stage: deploy
  script:
    - make deploy
  artifacts:
    paths:
      - _site
  only:
    - master
