name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: make build
    - uses: actions/upload-artifact@master
      with:
        name: site
        path: _site
